'use client';
import React from 'react';
import Link from 'next/link';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
import { motion } from 'framer-motion';

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <motion.div initial={{ opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} style={{ marginBottom: '2.5rem' }}>
    <h2 style={{ fontSize: '1.2rem', fontWeight: 900, color: '#0f172a', marginBottom: '0.75rem', letterSpacing: '-0.3px' }}>{title}</h2>
    <div style={{ color: 'var(--text-muted)', lineHeight: 1.8, fontWeight: 500 }}>{children}</div>
  </motion.div>
);

export default function TermsPage() {
  return (
    <main style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      <Nav />
      <section style={{ padding: 'clamp(120px, 18vw, 160px) 24px 80px', flex: 1 }}>
        <div className="container" style={{ maxWidth: '780px', margin: '0 auto' }}>
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} style={{ marginBottom: '3rem' }}>
            <span style={{ fontSize: '0.7rem', fontWeight: 900, color: 'var(--primary)', letterSpacing: '2px', textTransform: 'uppercase' }}>Legal</span>
            <h1 style={{ fontSize: 'clamp(2.2rem, 6vw, 3.5rem)', letterSpacing: '-1.5px', margin: '0.5rem 0 1rem' }}>Terms & <span className="text-gradient">Conditions</span></h1>
            <p style={{ color: 'var(--text-muted)', fontWeight: 500 }}>Last updated: April 2026</p>
          </motion.div>

          <div className="glass" style={{ background: 'white', borderRadius: '28px', padding: 'clamp(1.5rem, 6vw, 3.5rem)', border: '1px solid rgba(0,0,0,0.04)' }}>
            <Section title="1. Acceptance of Terms">
              <p>By accessing and using Sezapro ("the Platform"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please discontinue use of the Platform immediately.</p>
            </Section>
            <Section title="2. Description of Services">
              <p>Sezapro provides AI-powered construction cost estimation, material bill of quantities generation, procurement facilitation, and inventory management tools for construction professionals in Nigeria and globally. All estimates generated are indicative and based on current market data; actual costs may vary.</p>
            </Section>
            <Section title="3. User Accounts">
              <p>You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorised use of your account. Sezapro reserves the right to terminate accounts that violate these terms.</p>
            </Section>
            <Section title="4. Procurement & Orders">
              <p>Orders placed through Sezapro are facilitated via WhatsApp communication between you and our procurement team. Sezapro does not process online payments. All pricing is subject to confirmation by our team. Sezapro acts as a facilitator and is not responsible for material quality disputes with third-party suppliers.</p>
            </Section>
            <Section title="5. Estimation Accuracy">
              <p>All cost estimates generated by the Sezapro AI engine are based on approximate market rates and construction benchmarks. These figures are intended as planning guides only and should not be used as final project budgets without independent professional verification. Sezapro does not guarantee the accuracy of any estimate.</p>
            </Section>
            <Section title="6. Intellectual Property">
              <p>All content, technology, branding, and software on the Sezapro platform are the exclusive property of Seza Engineering Ltd and are protected under Nigerian and international intellectual property laws. You may not reproduce, distribute, or create derivative works without written permission.</p>
            </Section>
            <Section title="7. Limitation of Liability">
              <p>Sezapro shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of the platform, including but not limited to project cost overruns, procurement delays, or reliance on AI-generated estimates.</p>
            </Section>
            <Section title="8. Governing Law">
              <p>These terms are governed by the laws of the Federal Republic of Nigeria. Any disputes shall be resolved through the courts of Lagos State, Nigeria.</p>
            </Section>
            <Section title="9. Changes to Terms">
              <p>Sezapro reserves the right to update these Terms at any time. Continued use of the platform after such changes constitutes acceptance of the revised terms.</p>
            </Section>
            <Section title="10. Contact Us">
              <p>If you have any questions about these Terms, please contact us at <Link href="/contact" style={{ color: 'var(--primary)', fontWeight: 700 }}>contact@sezapro.com</Link></p>
            </Section>
            <Section title="11. Flexible Payment Plans (BNPL)">
              <p>
                Sezapro offers "Buy Now, Pay Later" (BNPL) options for qualified customers. By selecting a payment plan (3, 6, or 12 months), you agree to our credit vetting process. 
              </p>
              <p>
                Approval is at the sole discretion of Sezapro AI and our financing partners. Late payments may incur penalties and lead to the suspension of active material deliveries. Financing fees or markups are clearly stated at checkout and are non-refundable once the plan is activated.
              </p>
            </Section>
          </div>
        </div>
      </section>
      <Footer />
    </main>
  );
}
